// Placeholder for the file generated by the FlutterFire CLI.
//
// To enable push notifications (Firebase Cloud Messaging):
//
//   dart pub global activate flutterfire_cli
//   cd family_hub_app && flutterfire configure
//
// `flutterfire configure` OVERWRITES this file with the real per-platform
// [FirebaseOptions] and adds `android/app/google-services.json` +
// `ios/Runner/GoogleService-Info.plist` (and the google-services Gradle plugin).
// Do not hand-edit the generated version; re-run the command instead.
//
// Until then [DefaultFirebaseOptions.currentPlatform] throws an
// [UnsupportedError]. `main.dart` catches it, skips `Firebase.initializeApp`
// and the app runs without push: every method of `PushNotificationService` is
// a safe no-op while `Firebase.apps` is empty.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Stub - replaced by `flutterfire configure`.
abstract final class DefaultFirebaseOptions {
  /// Always throws until `flutterfire configure` has been run.
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'Run flutterfire configure - Firebase is not configured for this app, '
      'so push notifications are disabled. See lib/firebase_options.dart.',
    );
  }
}
